In [17]:
# Permite ajustar la anchura de la parte útil de la libreta (reduce los márgenes)
from IPython.core.display import display, HTML
display(HTML("<style>.container{ width:98% }</style>"))

/tmp/ipykernel_823045/1126351303.py:2: DeprecationWarning: Importing display from IPython.core.display is deprecated since IPython 7.14, please import from IPython display
  from IPython.core.display import display, HTML

In [2]:
## install required packages
!pip install swig
!pip install wrds
!pip install pyportfolioopt
## install finrl library
!pip install git+https://github.com/AI4Finance-Foundation/FinRL.git

Requirement already satisfied: swig in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (4.3.1)
Requirement already satisfied: wrds in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (3.3.0)
Requirement already satisfied: packaging<=24.2 in /home/danirm/.local/lib/python3.10/site-packages (from wrds) (23.2)
Requirement already satisfied: pandas<2.3,>=2.2 in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from wrds) (2.2.3)
Requirement already satisfied: psycopg2-binary<2.10,>=2.9 in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from wrds) (2.9.10)
Requirement already satisfied: sqlalchemy<2.1,>=2 in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from wrds) (2.0.40)
Requirement already satisfied: numpy>=1.22.4 in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from pandas<2.3,>=2.2->wrds) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/danirm/.local/lib/python3.10/site-packages (from pandas<2.3,>=2.2->wrds) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from pandas<2.3,>=2.2->wrds) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /home/danirm/.local/lib/python3.10/site-packages (from pandas<2.3,>=2.2->wrds) (2023.3)
Requirement already satisfied: greenlet>=1 in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from sqlalchemy<2.1,>=2->wrds) (3.2.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from sqlalchemy<2.1,>=2->wrds) (4.13.2)
Requirement already satisfied: six>=1.5 in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas<2.3,>=2.2->wrds) (1.17.0)
Requirement already satisfied: pyportfolioopt in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (1.5.6)
Requirement already satisfied: cvxpy>=1.1.19 in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from pyportfolioopt) (1.6.5)
Requirement already satisfied: ecos<3.0.0,>=2.0.14 in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from pyportfolioopt) (2.0.14)
Requirement already satisfied: numpy>=1.26.0 in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from pyportfolioopt) (1.26.4)
Requirement already satisfied: pandas>=0.19 in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from pyportfolioopt) (2.2.3)
Requirement already satisfied: plotly<6.0.0,>=5.0.0 in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from pyportfolioopt) (5.24.1)
Requirement already satisfied: scipy>=1.3 in /home/danirm/.local/lib/python3.10/site-packages (from pyportfolioopt) (1.11.3)
Requirement already satisfied: tenacity>=6.2.0 in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from plotly<6.0.0,>=5.0.0->pyportfolioopt) (9.1.2)
Requirement already satisfied: packaging in /home/danirm/.local/lib/python3.10/site-packages (from plotly<6.0.0,>=5.0.0->pyportfolioopt) (23.2)
Requirement already satisfied: osqp>=0.6.2 in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from cvxpy>=1.1.19->pyportfolioopt) (1.0.4)
Requirement already satisfied: clarabel>=0.5.0 in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from cvxpy>=1.1.19->pyportfolioopt) (0.10.0)
Requirement already satisfied: scs>=3.2.4.post1 in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from cvxpy>=1.1.19->pyportfolioopt) (3.2.7.post2)
Requirement already satisfied: jinja2 in /home/danirm/.local/lib/python3.10/site-packages (from osqp>=0.6.2->cvxpy>=1.1.19->pyportfolioopt) (3.1.2)
Requirement already satisfied: setuptools in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from osqp>=0.6.2->cvxpy>=1.1.19->pyportfolioopt) (78.1.1)
Requirement already satisfied: joblib in /home/danirm/.local/lib/python3.10/site-packages (from osqp>=0.6.2->cvxpy>=1.1.19->pyportfolioopt) (1.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/danirm/.local/lib/python3.10/site-packages (from pandas>=0.19->pyportfolioopt) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from pandas>=0.19->pyportfolioopt) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /home/danirm/.local/lib/python3.10/site-packages (from pandas>=0.19->pyportfolioopt) (2023.3)
Requirement already satisfied: six>=1.5 in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas>=0.19->pyportfolioopt) (1.17.0)
Requirement already satisfied: MarkupSafe>=2.0 in /home/danirm/.local/lib/python3.10/site-packages (from jinja2->osqp>=0.6.2->cvxpy>=1.1.19->pyportfolioopt) (2.1.5)
Collecting git+https://github.com/AI4Finance-Foundation/FinRL.git
  Cloning https://github.com/AI4Finance-Foundation/FinRL.git to /tmp/pip-req-build-wqmijq_y
  Running command git clone --filter=blob:none --quiet https://github.com/AI4Finance-Foundation/FinRL.git /tmp/pip-req-build-wqmijq_y
  Resolved https://github.com/AI4Finance-Foundation/FinRL.git to commit 9175621d1235a335a667ee4796d7722e555a9e78
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: alpaca-py<0.38,>=0.37 in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from finrl==0.3.8) (0.37.0)
Requirement already satisfied: alpaca-trade-api<4,>=3 in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from finrl==0.3.8) (3.2.0)
Requirement already satisfied: ccxt<4,>=3 in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from finrl==0.3.8) (3.1.60)
Collecting elegantrl@ git+https://github.com/AI4Finance-Foundation/ElegantRL.git (from finrl==0.3.8)
  Cloning https://github.com/AI4Finance-Foundation/ElegantRL.git to /tmp/pip-install-yrcn7_r5/elegantrl_931fedc81ade4468a6a5213c4b2a9846
  Running command git clone --filter=blob:none --quiet https://github.com/AI4Finance-Foundation/ElegantRL.git /tmp/pip-install-yrcn7_r5/elegantrl_931fedc81ade4468a6a5213c4b2a9846
  Resolved https://github.com/AI4Finance-Foundation/ElegantRL.git to commit 8ea76afc3e7f1564ae9f0e69e70254116d575fe9
  Preparing metadata (setup.py) ... done
Requirement already satisfied: jqdatasdk<2,>=1 in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from finrl==0.3.8) (1.9.7)
Requirement already satisfied: pyfolio-reloaded<0.10,>=0.9 in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from finrl==0.3.8) (0.9.8)
Requirement already satisfied: pyportfolioopt<2,>=1 in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from finrl==0.3.8) (1.5.6)
Requirement already satisfied: ray<3,>=2 in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from ray[default,tune]<3,>=2->finrl==0.3.8) (2.46.0)
Requirement already satisfied: scikit-learn<2,>=1 in /home/danirm/.local/lib/python3.10/site-packages (from finrl==0.3.8) (1.5.2)
Requirement already satisfied: selenium<5,>=4 in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from finrl==0.3.8) (4.32.0)
Requirement already satisfied: stable-baselines3>=2.0.0a5 in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from stable-baselines3[extra]>=2.0.0a5->finrl==0.3.8) (2.6.0)
Requirement already satisfied: stockstats<0.6,>=0.5 in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from finrl==0.3.8) (0.5.4)
Requirement already satisfied: webdriver-manager<5,>=4 in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from finrl==0.3.8) (4.0.2)
Requirement already satisfied: wrds<4,>=3 in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from finrl==0.3.8) (3.3.0)
Requirement already satisfied: yfinance<0.3,>=0.2 in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from finrl==0.3.8) (0.2.58)
Requirement already satisfied: th in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from elegantrl@ git+https://github.com/AI4Finance-Foundation/ElegantRL.git->finrl==0.3.8) (0.4.1)
Requirement already satisfied: numpy in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from elegantrl@ git+https://github.com/AI4Finance-Foundation/ElegantRL.git->finrl==0.3.8) (1.26.4)
Requirement already satisfied: gymnasium in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from elegantrl@ git+https://github.com/AI4Finance-Foundation/ElegantRL.git->finrl==0.3.8) (1.1.1)
Requirement already satisfied: matplotlib in /home/danirm/.local/lib/python3.10/site-packages (from elegantrl@ git+https://github.com/AI4Finance-Foundation/ElegantRL.git->finrl==0.3.8) (3.8.0)
Requirement already satisfied: msgpack<2.0.0,>=1.0.3 in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from alpaca-py<0.38,>=0.37->finrl==0.3.8) (1.0.3)
Requirement already satisfied: pandas>=1.5.3 in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from alpaca-py<0.38,>=0.37->finrl==0.3.8) (2.2.3)
Requirement already satisfied: pydantic<3.0.0,>=2.0.3 in /home/danirm/.local/lib/python3.10/site-packages (from alpaca-py<0.38,>=0.37->finrl==0.3.8) (2.9.2)
Requirement already satisfied: requests<3.0.0,>=2.30.0 in /home/danirm/.local/lib/python3.10/site-packages (from alpaca-py<0.38,>=0.37->finrl==0.3.8) (2.31.0)
Requirement already satisfied: sseclient-py<2.0.0,>=1.7.2 in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from alpaca-py<0.38,>=0.37->finrl==0.3.8) (1.8.0)
Requirement already satisfied: websockets>=10.4 in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from alpaca-py<0.38,>=0.37->finrl==0.3.8) (10.4)
Requirement already satisfied: urllib3<2,>1.24 in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from alpaca-trade-api<4,>=3->finrl==0.3.8) (1.26.20)
Requirement already satisfied: websocket-client<2,>=0.56.0 in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from alpaca-trade-api<4,>=3->finrl==0.3.8) (1.8.0)
Requirement already satisfied: aiohttp<4,>=3.8.3 in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from alpaca-trade-api<4,>=3->finrl==0.3.8) (3.11.18)
Requirement already satisfied: PyYAML==6.0.1 in /home/danirm/.local/lib/python3.10/site-packages (from alpaca-trade-api<4,>=3->finrl==0.3.8) (6.0.1)
Requirement already satisfied: deprecation==2.1.0 in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from alpaca-trade-api<4,>=3->finrl==0.3.8) (2.1.0)
Requirement already satisfied: packaging in /home/danirm/.local/lib/python3.10/site-packages (from deprecation==2.1.0->alpaca-trade-api<4,>=3->finrl==0.3.8) (23.2)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from aiohttp<4,>=3.8.3->alpaca-trade-api<4,>=3->finrl==0.3.8) (2.6.1)
Requirement already satisfied: aiosignal>=1.1.2 in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from aiohttp<4,>=3.8.3->alpaca-trade-api<4,>=3->finrl==0.3.8) (1.3.2)
Requirement already satisfied: async-timeout<6.0,>=4.0 in /home/danirm/.local/lib/python3.10/site-packages (from aiohttp<4,>=3.8.3->alpaca-trade-api<4,>=3->finrl==0.3.8) (4.0.3)
Requirement already satisfied: attrs>=17.3.0 in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from aiohttp<4,>=3.8.3->alpaca-trade-api<4,>=3->finrl==0.3.8) (25.3.0)

Requirement already satisfied: frozenlist>=1.1.1 in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from aiohttp<4,>=3.8.3->alpaca-trade-api<4,>=3->finrl==0.3.8) (1.6.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from aiohttp<4,>=3.8.3->alpaca-trade-api<4,>=3->finrl==0.3.8) (6.4.3)
Requirement already satisfied: propcache>=0.2.0 in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from aiohttp<4,>=3.8.3->alpaca-trade-api<4,>=3->finrl==0.3.8) (0.3.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from aiohttp<4,>=3.8.3->alpaca-trade-api<4,>=3->finrl==0.3.8) (1.20.0)
Requirement already satisfied: setuptools>=60.9.0 in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from ccxt<4,>=3->finrl==0.3.8) (78.1.1)
Requirement already satisfied: certifi>=2018.1.18 in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from ccxt<4,>=3->finrl==0.3.8) (2025.4.26)
Requirement already satisfied: cryptography>=2.6.1 in /home/danirm/.local/lib/python3.10/site-packages (from ccxt<4,>=3->finrl==0.3.8) (42.0.7)
Requirement already satisfied: aiodns>=1.1.1 in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from ccxt<4,>=3->finrl==0.3.8) (3.4.0)
Requirement already satisfied: six in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from jqdatasdk<2,>=1->finrl==0.3.8) (1.17.0)
Requirement already satisfied: SQLAlchemy>=1.2.8 in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from jqdatasdk<2,>=1->finrl==0.3.8) (2.0.40)
Requirement already satisfied: pymysql>=0.7.6 in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from jqdatasdk<2,>=1->finrl==0.3.8) (1.1.1)
Requirement already satisfied: thriftpy2!=0.5.1,>=0.3.9 in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from jqdatasdk<2,>=1->finrl==0.3.8) (0.5.2)
Requirement already satisfied: typing-extensions>=4.1.0 in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from multidict<7.0,>=4.5->aiohttp<4,>=3.8.3->alpaca-trade-api<4,>=3->finrl==0.3.8) (4.13.2)
Requirement already satisfied: annotated-types>=0.6.0 in /home/danirm/.local/lib/python3.10/site-packages (from pydantic<3.0.0,>=2.0.3->alpaca-py<0.38,>=0.37->finrl==0.3.8) (0.7.0)
Requirement already satisfied: pydantic-core==2.23.4 in /home/danirm/.local/lib/python3.10/site-packages (from pydantic<3.0.0,>=2.0.3->alpaca-py<0.38,>=0.37->finrl==0.3.8) (2.23.4)
Requirement already satisfied: ipython>=3.2.3 in /home/danirm/.local/lib/python3.10/site-packages (from pyfolio-reloaded<0.10,>=0.9->finrl==0.3.8) (8.17.2)
Requirement already satisfied: pytz>=2014.10 in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from pyfolio-reloaded<0.10,>=0.9->finrl==0.3.8) (2025.2)
Requirement already satisfied: scipy>=0.14.0 in /home/danirm/.local/lib/python3.10/site-packages (from pyfolio-reloaded<0.10,>=0.9->finrl==0.3.8) (1.11.3)
Requirement already satisfied: seaborn>=0.7.1 in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from pyfolio-reloaded<0.10,>=0.9->finrl==0.3.8) (0.13.2)
Requirement already satisfied: empyrical-reloaded>=0.5.9 in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from pyfolio-reloaded<0.10,>=0.9->finrl==0.3.8) (0.5.11)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/danirm/.local/lib/python3.10/site-packages (from pandas>=1.5.3->alpaca-py<0.38,>=0.37->finrl==0.3.8) (2.8.2)
Requirement already satisfied: tzdata>=2022.7 in /home/danirm/.local/lib/python3.10/site-packages (from pandas>=1.5.3->alpaca-py<0.38,>=0.37->finrl==0.3.8) (2023.3)
Requirement already satisfied: cvxpy>=1.1.19 in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from pyportfolioopt<2,>=1->finrl==0.3.8) (1.6.5)
Requirement already satisfied: ecos<3.0.0,>=2.0.14 in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from pyportfolioopt<2,>=1->finrl==0.3.8) (2.0.14)
Requirement already satisfied: plotly<6.0.0,>=5.0.0 in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from pyportfolioopt<2,>=1->finrl==0.3.8) (5.24.1)
Requirement already satisfied: tenacity>=6.2.0 in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from plotly<6.0.0,>=5.0.0->pyportfolioopt<2,>=1->finrl==0.3.8) (9.1.2)
Requirement already satisfied: click>=7.0 in /home/danirm/.local/lib/python3.10/site-packages (from ray<3,>=2->ray[default,tune]<3,>=2->finrl==0.3.8) (8.1.7)
Requirement already satisfied: filelock in /home/danirm/.local/lib/python3.10/site-packages (from ray<3,>=2->ray[default,tune]<3,>=2->finrl==0.3.8) (3.14.0)
Requirement already satisfied: jsonschema in /home/danirm/.local/lib/python3.10/site-packages (from ray<3,>=2->ray[default,tune]<3,>=2->finrl==0.3.8) (4.19.2)
Requirement already satisfied: protobuf!=3.19.5,>=3.15.3 in /home/danirm/.local/lib/python3.10/site-packages (from ray<3,>=2->ray[default,tune]<3,>=2->finrl==0.3.8) (5.28.2)
Requirement already satisfied: tensorboardX>=1.9 in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from ray[default,tune]<3,>=2->finrl==0.3.8) (2.6.2.2)
Requirement already satisfied: pyarrow>=9.0.0 in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from ray[default,tune]<3,>=2->finrl==0.3.8) (20.0.0)
Requirement already satisfied: fsspec in /home/danirm/.local/lib/python3.10/site-packages (from ray[default,tune]<3,>=2->finrl==0.3.8) (2024.9.0)
Requirement already satisfied: aiohttp_cors in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from ray[default,tune]<3,>=2->finrl==0.3.8) (0.8.1)
Requirement already satisfied: colorful in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from ray[default,tune]<3,>=2->finrl==0.3.8) (0.5.6)
Requirement already satisfied: py-spy>=0.2.0 in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from ray[default,tune]<3,>=2->finrl==0.3.8) (0.4.0)
Requirement already satisfied: grpcio>=1.42.0 in /home/danirm/.local/lib/python3.10/site-packages (from ray[default,tune]<3,>=2->finrl==0.3.8) (1.66.2)
Requirement already satisfied: opencensus in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from ray[default,tune]<3,>=2->finrl==0.3.8) (0.11.4)
Requirement already satisfied: prometheus_client>=0.7.1 in /home/danirm/.local/lib/python3.10/site-packages (from ray[default,tune]<3,>=2->finrl==0.3.8) (0.18.0)
Requirement already satisfied: smart_open in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from ray[default,tune]<3,>=2->finrl==0.3.8) (7.1.0)
Requirement already satisfied: virtualenv!=20.21.1,>=20.0.24 in /home/danirm/.local/lib/python3.10/site-packages (from ray[default,tune]<3,>=2->finrl==0.3.8) (20.26.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/danirm/.local/lib/python3.10/site-packages (from requests<3.0.0,>=2.30.0->alpaca-py<0.38,>=0.37->finrl==0.3.8) (3.1.0)
Requirement already satisfied: idna<4,>=2.5 in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from requests<3.0.0,>=2.30.0->alpaca-py<0.38,>=0.37->finrl==0.3.8) (3.10)
Requirement already satisfied: joblib>=1.2.0 in /home/danirm/.local/lib/python3.10/site-packages (from scikit-learn<2,>=1->finrl==0.3.8) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /home/danirm/.local/lib/python3.10/site-packages (from scikit-learn<2,>=1->finrl==0.3.8) (3.5.0)
Requirement already satisfied: trio~=0.17 in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from selenium<5,>=4->finrl==0.3.8) (0.30.0)
Requirement already satisfied: trio-websocket~=0.9 in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from selenium<5,>=4->finrl==0.3.8) (0.12.2)
Requirement already satisfied: sortedcontainers in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from trio~=0.17->selenium<5,>=4->finrl==0.3.8) (2.4.0)
Requirement already satisfied: outcome in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from trio~=0.17->selenium<5,>=4->finrl==0.3.8) (1.3.0.post0)
Requirement already satisfied: sniffio>=1.3.0 in /home/danirm/.local/lib/python3.10/site-packages (from trio~=0.17->selenium<5,>=4->finrl==0.3.8) (1.3.0)
Requirement already satisfied: exceptiongroup in /home/danirm/.local/lib/python3.10/site-packages (from trio~=0.17->selenium<5,>=4->finrl==0.3.8) (1.1.3)
Requirement already satisfied: wsproto>=0.14 in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from trio-websocket~=0.9->selenium<5,>=4->finrl==0.3.8) (1.2.0)
Requirement already satisfied: PySocks!=1.5.7,<2.0,>=1.5.6 in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from urllib3[socks]<3,>=1.26->selenium<5,>=4->finrl==0.3.8) (1.7.1)
Requirement already satisfied: python-dotenv in /home/danirm/.local/lib/python3.10/site-packages (from webdriver-manager<5,>=4->finrl==0.3.8) (0.21.1)
Requirement already satisfied: psycopg2-binary<2.10,>=2.9 in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from wrds<4,>=3->finrl==0.3.8) (2.9.10)

Requirement already satisfied: greenlet>=1 in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from SQLAlchemy>=1.2.8->jqdatasdk<2,>=1->finrl==0.3.8) (3.2.2)
Requirement already satisfied: multitasking>=0.0.7 in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from yfinance<0.3,>=0.2->finrl==0.3.8) (0.0.11)
Requirement already satisfied: platformdirs>=2.0.0 in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from yfinance<0.3,>=0.2->finrl==0.3.8) (4.3.8)
Requirement already satisfied: frozendict>=2.3.4 in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from yfinance<0.3,>=0.2->finrl==0.3.8) (2.4.6)
Requirement already satisfied: peewee>=3.16.2 in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from yfinance<0.3,>=0.2->finrl==0.3.8) (3.17.3)
Requirement already satisfied: beautifulsoup4>=4.11.1 in /home/danirm/.local/lib/python3.10/site-packages (from yfinance<0.3,>=0.2->finrl==0.3.8) (4.12.2)
Requirement already satisfied: curl_cffi>=0.7 in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from yfinance<0.3,>=0.2->finrl==0.3.8) (0.10.0)
Requirement already satisfied: pycares>=4.0.0 in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from aiodns>=1.1.1->ccxt<4,>=3->finrl==0.3.8) (4.8.0)
Requirement already satisfied: soupsieve>1.2 in /home/danirm/.local/lib/python3.10/site-packages (from beautifulsoup4>=4.11.1->yfinance<0.3,>=0.2->finrl==0.3.8) (2.5)
Requirement already satisfied: cffi>=1.12 in /home/danirm/.local/lib/python3.10/site-packages (from cryptography>=2.6.1->ccxt<4,>=3->finrl==0.3.8) (1.16.0)
Requirement already satisfied: pycparser in /home/danirm/.local/lib/python3.10/site-packages (from cffi>=1.12->cryptography>=2.6.1->ccxt<4,>=3->finrl==0.3.8) (2.21)
Requirement already satisfied: osqp>=0.6.2 in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from cvxpy>=1.1.19->pyportfolioopt<2,>=1->finrl==0.3.8) (1.0.4)
Requirement already satisfied: clarabel>=0.5.0 in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from cvxpy>=1.1.19->pyportfolioopt<2,>=1->finrl==0.3.8) (0.10.0)
Requirement already satisfied: scs>=3.2.4.post1 in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from cvxpy>=1.1.19->pyportfolioopt<2,>=1->finrl==0.3.8) (3.2.7.post2)
Requirement already satisfied: bottleneck>=1.3.0 in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from empyrical-reloaded>=0.5.9->pyfolio-reloaded<0.10,>=0.9->finrl==0.3.8) (1.4.2)
Requirement already satisfied: decorator in /home/danirm/.local/lib/python3.10/site-packages (from ipython>=3.2.3->pyfolio-reloaded<0.10,>=0.9->finrl==0.3.8) (5.1.1)
Requirement already satisfied: jedi>=0.16 in /home/danirm/.local/lib/python3.10/site-packages (from ipython>=3.2.3->pyfolio-reloaded<0.10,>=0.9->finrl==0.3.8) (0.19.1)
Requirement already satisfied: matplotlib-inline in /home/danirm/.local/lib/python3.10/site-packages (from ipython>=3.2.3->pyfolio-reloaded<0.10,>=0.9->finrl==0.3.8) (0.1.6)
Requirement already satisfied: prompt-toolkit!=3.0.37,<3.1.0,>=3.0.30 in /home/danirm/.local/lib/python3.10/site-packages (from ipython>=3.2.3->pyfolio-reloaded<0.10,>=0.9->finrl==0.3.8) (3.0.40)
Requirement already satisfied: pygments>=2.4.0 in /home/danirm/.local/lib/python3.10/site-packages (from ipython>=3.2.3->pyfolio-reloaded<0.10,>=0.9->finrl==0.3.8) (2.16.1)
Requirement already satisfied: stack-data in /home/danirm/.local/lib/python3.10/site-packages (from ipython>=3.2.3->pyfolio-reloaded<0.10,>=0.9->finrl==0.3.8) (0.6.3)
Requirement already satisfied: traitlets>=5 in /home/danirm/.local/lib/python3.10/site-packages (from ipython>=3.2.3->pyfolio-reloaded<0.10,>=0.9->finrl==0.3.8) (5.13.0)
Requirement already satisfied: pexpect>4.3 in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from ipython>=3.2.3->pyfolio-reloaded<0.10,>=0.9->finrl==0.3.8) (4.9.0)
Requirement already satisfied: wcwidth in /home/danirm/.local/lib/python3.10/site-packages (from prompt-toolkit!=3.0.37,<3.1.0,>=3.0.30->ipython>=3.2.3->pyfolio-reloaded<0.10,>=0.9->finrl==0.3.8) (0.2.9)
Requirement already satisfied: parso<0.9.0,>=0.8.3 in /home/danirm/.local/lib/python3.10/site-packages (from jedi>=0.16->ipython>=3.2.3->pyfolio-reloaded<0.10,>=0.9->finrl==0.3.8) (0.8.3)
Requirement already satisfied: contourpy>=1.0.1 in /home/danirm/.local/lib/python3.10/site-packages (from matplotlib->elegantrl@ git+https://github.com/AI4Finance-Foundation/ElegantRL.git->finrl==0.3.8) (1.1.1)
Requirement already satisfied: cycler>=0.10 in /home/danirm/.local/lib/python3.10/site-packages (from matplotlib->elegantrl@ git+https://github.com/AI4Finance-Foundation/ElegantRL.git->finrl==0.3.8) (0.12.0)
Requirement already satisfied: fonttools>=4.22.0 in /home/danirm/.local/lib/python3.10/site-packages (from matplotlib->elegantrl@ git+https://github.com/AI4Finance-Foundation/ElegantRL.git->finrl==0.3.8) (4.43.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /home/danirm/.local/lib/python3.10/site-packages (from matplotlib->elegantrl@ git+https://github.com/AI4Finance-Foundation/ElegantRL.git->finrl==0.3.8) (1.4.5)
Requirement already satisfied: pillow>=6.2.0 in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from matplotlib->elegantrl@ git+https://github.com/AI4Finance-Foundation/ElegantRL.git->finrl==0.3.8) (11.2.1)
Requirement already satisfied: pyparsing>=2.3.1 in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from matplotlib->elegantrl@ git+https://github.com/AI4Finance-Foundation/ElegantRL.git->finrl==0.3.8) (3.2.3)
Requirement already satisfied: jinja2 in /home/danirm/.local/lib/python3.10/site-packages (from osqp>=0.6.2->cvxpy>=1.1.19->pyportfolioopt<2,>=1->finrl==0.3.8) (3.1.2)
Requirement already satisfied: ptyprocess>=0.5 in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from pexpect>4.3->ipython>=3.2.3->pyfolio-reloaded<0.10,>=0.9->finrl==0.3.8) (0.7.0)
Requirement already satisfied: torch<3.0,>=2.3 in /home/danirm/.local/lib/python3.10/site-packages (from stable-baselines3>=2.0.0a5->stable-baselines3[extra]>=2.0.0a5->finrl==0.3.8) (2.4.1)
Requirement already satisfied: cloudpickle in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from stable-baselines3>=2.0.0a5->stable-baselines3[extra]>=2.0.0a5->finrl==0.3.8) (3.1.1)
Requirement already satisfied: farama-notifications>=0.0.1 in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from gymnasium->elegantrl@ git+https://github.com/AI4Finance-Foundation/ElegantRL.git->finrl==0.3.8) (0.0.4)
Requirement already satisfied: sympy in /home/danirm/.local/lib/python3.10/site-packages (from torch<3.0,>=2.3->stable-baselines3>=2.0.0a5->stable-baselines3[extra]>=2.0.0a5->finrl==0.3.8) (1.13.3)
Requirement already satisfied: networkx in /home/danirm/.local/lib/python3.10/site-packages (from torch<3.0,>=2.3->stable-baselines3>=2.0.0a5->stable-baselines3[extra]>=2.0.0a5->finrl==0.3.8) (3.2.1)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.1.105 in /home/danirm/.local/lib/python3.10/site-packages (from torch<3.0,>=2.3->stable-baselines3>=2.0.0a5->stable-baselines3[extra]>=2.0.0a5->finrl==0.3.8) (12.1.105)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.1.105 in /home/danirm/.local/lib/python3.10/site-packages (from torch<3.0,>=2.3->stable-baselines3>=2.0.0a5->stable-baselines3[extra]>=2.0.0a5->finrl==0.3.8) (12.1.105)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.1.105 in /home/danirm/.local/lib/python3.10/site-packages (from torch<3.0,>=2.3->stable-baselines3>=2.0.0a5->stable-baselines3[extra]>=2.0.0a5->finrl==0.3.8) (12.1.105)
Requirement already satisfied: nvidia-cudnn-cu12==9.1.0.70 in /home/danirm/.local/lib/python3.10/site-packages (from torch<3.0,>=2.3->stable-baselines3>=2.0.0a5->stable-baselines3[extra]>=2.0.0a5->finrl==0.3.8) (9.1.0.70)
Requirement already satisfied: nvidia-cublas-cu12==12.1.3.1 in /home/danirm/.local/lib/python3.10/site-packages (from torch<3.0,>=2.3->stable-baselines3>=2.0.0a5->stable-baselines3[extra]>=2.0.0a5->finrl==0.3.8) (12.1.3.1)
Requirement already satisfied: nvidia-cufft-cu12==11.0.2.54 in /home/danirm/.local/lib/python3.10/site-packages (from torch<3.0,>=2.3->stable-baselines3>=2.0.0a5->stable-baselines3[extra]>=2.0.0a5->finrl==0.3.8) (11.0.2.54)
Requirement already satisfied: nvidia-curand-cu12==10.3.2.106 in /home/danirm/.local/lib/python3.10/site-packages (from torch<3.0,>=2.3->stable-baselines3>=2.0.0a5->stable-baselines3[extra]>=2.0.0a5->finrl==0.3.8) (10.3.2.106)
Requirement already satisfied: nvidia-cusolver-cu12==11.4.5.107 in /home/danirm/.local/lib/python3.10/site-packages (from torch<3.0,>=2.3->stable-baselines3>=2.0.0a5->stable-baselines3[extra]>=2.0.0a5->finrl==0.3.8) (11.4.5.107)
Requirement already satisfied: nvidia-cusparse-cu12==12.1.0.106 in /home/danirm/.local/lib/python3.10/site-packages (from torch<3.0,>=2.3->stable-baselines3>=2.0.0a5->stable-baselines3[extra]>=2.0.0a5->finrl==0.3.8) (12.1.0.106)
Requirement already satisfied: nvidia-nccl-cu12==2.20.5 in /home/danirm/.local/lib/python3.10/site-packages (from torch<3.0,>=2.3->stable-baselines3>=2.0.0a5->stable-baselines3[extra]>=2.0.0a5->finrl==0.3.8) (2.20.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.1.105 in /home/danirm/.local/lib/python3.10/site-packages (from torch<3.0,>=2.3->stable-baselines3>=2.0.0a5->stable-baselines3[extra]>=2.0.0a5->finrl==0.3.8) (12.1.105)
Requirement already satisfied: triton==3.0.0 in /home/danirm/.local/lib/python3.10/site-packages (from torch<3.0,>=2.3->stable-baselines3>=2.0.0a5->stable-baselines3[extra]>=2.0.0a5->finrl==0.3.8) (3.0.0)
Requirement already satisfied: nvidia-nvjitlink-cu12 in /home/danirm/.local/lib/python3.10/site-packages (from nvidia-cusolver-cu12==11.4.5.107->torch<3.0,>=2.3->stable-baselines3>=2.0.0a5->stable-baselines3[extra]>=2.0.0a5->finrl==0.3.8) (12.6.77)

Requirement already satisfied: opencv-python in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from stable-baselines3[extra]>=2.0.0a5->finrl==0.3.8) (4.11.0.86)
Requirement already satisfied: pygame in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from stable-baselines3[extra]>=2.0.0a5->finrl==0.3.8) (2.6.1)
Requirement already satisfied: tensorboard>=2.9.1 in /home/danirm/.local/lib/python3.10/site-packages (from stable-baselines3[extra]>=2.0.0a5->finrl==0.3.8) (2.17.1)
Requirement already satisfied: psutil in /home/danirm/.local/lib/python3.10/site-packages (from stable-baselines3[extra]>=2.0.0a5->finrl==0.3.8) (5.9.6)
Requirement already satisfied: tqdm in /home/danirm/.local/lib/python3.10/site-packages (from stable-baselines3[extra]>=2.0.0a5->finrl==0.3.8) (4.66.5)
Requirement already satisfied: rich in /home/danirm/.local/lib/python3.10/site-packages (from stable-baselines3[extra]>=2.0.0a5->finrl==0.3.8) (12.5.1)
Requirement already satisfied: ale-py>=0.9.0 in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from stable-baselines3[extra]>=2.0.0a5->finrl==0.3.8) (0.11.0)
Requirement already satisfied: absl-py>=0.4 in /home/danirm/.local/lib/python3.10/site-packages (from tensorboard>=2.9.1->stable-baselines3[extra]>=2.0.0a5->finrl==0.3.8) (2.1.0)
Requirement already satisfied: markdown>=2.6.8 in /home/danirm/.local/lib/python3.10/site-packages (from tensorboard>=2.9.1->stable-baselines3[extra]>=2.0.0a5->finrl==0.3.8) (3.7)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /home/danirm/.local/lib/python3.10/site-packages (from tensorboard>=2.9.1->stable-baselines3[extra]>=2.0.0a5->finrl==0.3.8) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /home/danirm/.local/lib/python3.10/site-packages (from tensorboard>=2.9.1->stable-baselines3[extra]>=2.0.0a5->finrl==0.3.8) (3.0.4)
Requirement already satisfied: Cython>=3.0.10 in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from thriftpy2!=0.5.1,>=0.3.9->jqdatasdk<2,>=1->finrl==0.3.8) (3.1.0)
Requirement already satisfied: ply<4.0,>=3.4 in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from thriftpy2!=0.5.1,>=0.3.9->jqdatasdk<2,>=1->finrl==0.3.8) (3.11)
Requirement already satisfied: distlib<1,>=0.3.7 in /home/danirm/.local/lib/python3.10/site-packages (from virtualenv!=20.21.1,>=20.0.24->ray[default,tune]<3,>=2->finrl==0.3.8) (0.3.8)
Requirement already satisfied: MarkupSafe>=2.1.1 in /home/danirm/.local/lib/python3.10/site-packages (from werkzeug>=1.0.1->tensorboard>=2.9.1->stable-baselines3[extra]>=2.0.0a5->finrl==0.3.8) (2.1.5)
Requirement already satisfied: h11<1,>=0.9.0 in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium<5,>=4->finrl==0.3.8) (0.16.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /home/danirm/.local/lib/python3.10/site-packages (from jsonschema->ray<3,>=2->ray[default,tune]<3,>=2->finrl==0.3.8) (2023.7.1)
Requirement already satisfied: referencing>=0.28.4 in /home/danirm/.local/lib/python3.10/site-packages (from jsonschema->ray<3,>=2->ray[default,tune]<3,>=2->finrl==0.3.8) (0.30.2)
Requirement already satisfied: rpds-py>=0.7.1 in /home/danirm/.local/lib/python3.10/site-packages (from jsonschema->ray<3,>=2->ray[default,tune]<3,>=2->finrl==0.3.8) (0.12.0)
Requirement already satisfied: opencensus-context>=0.1.3 in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from opencensus->ray[default,tune]<3,>=2->finrl==0.3.8) (0.1.3)
Requirement already satisfied: google-api-core<3.0.0,>=1.0.0 in /home/danirm/.local/lib/python3.10/site-packages (from opencensus->ray[default,tune]<3,>=2->finrl==0.3.8) (2.21.0)
Requirement already satisfied: googleapis-common-protos<2.0.dev0,>=1.56.2 in /home/danirm/.local/lib/python3.10/site-packages (from google-api-core<3.0.0,>=1.0.0->opencensus->ray[default,tune]<3,>=2->finrl==0.3.8) (1.65.0)
Requirement already satisfied: proto-plus<2.0.0dev,>=1.22.3 in /home/danirm/.local/lib/python3.10/site-packages (from google-api-core<3.0.0,>=1.0.0->opencensus->ray[default,tune]<3,>=2->finrl==0.3.8) (1.24.0)
Requirement already satisfied: google-auth<3.0.dev0,>=2.14.1 in /home/danirm/.local/lib/python3.10/site-packages (from google-api-core<3.0.0,>=1.0.0->opencensus->ray[default,tune]<3,>=2->finrl==0.3.8) (2.35.0)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /home/danirm/.local/lib/python3.10/site-packages (from google-auth<3.0.dev0,>=2.14.1->google-api-core<3.0.0,>=1.0.0->opencensus->ray[default,tune]<3,>=2->finrl==0.3.8) (5.5.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/danirm/.local/lib/python3.10/site-packages (from google-auth<3.0.dev0,>=2.14.1->google-api-core<3.0.0,>=1.0.0->opencensus->ray[default,tune]<3,>=2->finrl==0.3.8) (0.4.1)
Requirement already satisfied: rsa<5,>=3.1.4 in /home/danirm/.local/lib/python3.10/site-packages (from google-auth<3.0.dev0,>=2.14.1->google-api-core<3.0.0,>=1.0.0->opencensus->ray[default,tune]<3,>=2->finrl==0.3.8) (4.9)
Requirement already satisfied: pyasn1>=0.1.3 in /home/danirm/.local/lib/python3.10/site-packages (from rsa<5,>=3.1.4->google-auth<3.0.dev0,>=2.14.1->google-api-core<3.0.0,>=1.0.0->opencensus->ray[default,tune]<3,>=2->finrl==0.3.8) (0.6.1)
Requirement already satisfied: commonmark<0.10.0,>=0.9.0 in /home/danirm/.local/lib/python3.10/site-packages (from rich->stable-baselines3[extra]>=2.0.0a5->finrl==0.3.8) (0.9.1)
Requirement already satisfied: wrapt in /home/danirm/.local/lib/python3.10/site-packages (from smart_open->ray[default,tune]<3,>=2->finrl==0.3.8) (1.16.0)
Requirement already satisfied: executing>=1.2.0 in /home/danirm/.local/lib/python3.10/site-packages (from stack-data->ipython>=3.2.3->pyfolio-reloaded<0.10,>=0.9->finrl==0.3.8) (2.0.1)
Requirement already satisfied: asttokens>=2.1.0 in /home/danirm/.local/lib/python3.10/site-packages (from stack-data->ipython>=3.2.3->pyfolio-reloaded<0.10,>=0.9->finrl==0.3.8) (2.4.1)
Requirement already satisfied: pure-eval in /home/danirm/.local/lib/python3.10/site-packages (from stack-data->ipython>=3.2.3->pyfolio-reloaded<0.10,>=0.9->finrl==0.3.8) (0.2.2)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /home/danirm/.local/lib/python3.10/site-packages (from sympy->torch<3.0,>=2.3->stable-baselines3>=2.0.0a5->stable-baselines3[extra]>=2.0.0a5->finrl==0.3.8) (1.3.0)
Requirement already satisfied: niltype<2.0,>=0.3 in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from th->elegantrl@ git+https://github.com/AI4Finance-Foundation/ElegantRL.git->finrl==0.3.8) (1.0.2)

In [3]:
!pip install yfinance

Requirement already satisfied: yfinance in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (0.2.58)
Requirement already satisfied: pandas>=1.3.0 in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from yfinance) (2.2.3)
Requirement already satisfied: numpy>=1.16.5 in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from yfinance) (1.26.4)
Requirement already satisfied: requests>=2.31 in /home/danirm/.local/lib/python3.10/site-packages (from yfinance) (2.31.0)
Requirement already satisfied: multitasking>=0.0.7 in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from yfinance) (0.0.11)
Requirement already satisfied: platformdirs>=2.0.0 in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from yfinance) (4.3.8)
Requirement already satisfied: pytz>=2022.5 in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from yfinance) (2025.2)
Requirement already satisfied: frozendict>=2.3.4 in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from yfinance) (2.4.6)
Requirement already satisfied: peewee>=3.16.2 in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from yfinance) (3.17.3)
Requirement already satisfied: beautifulsoup4>=4.11.1 in /home/danirm/.local/lib/python3.10/site-packages (from yfinance) (4.12.2)
Requirement already satisfied: curl_cffi>=0.7 in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from yfinance) (0.10.0)
Requirement already satisfied: soupsieve>1.2 in /home/danirm/.local/lib/python3.10/site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.5)
Requirement already satisfied: cffi>=1.12.0 in /home/danirm/.local/lib/python3.10/site-packages (from curl_cffi>=0.7->yfinance) (1.16.0)
Requirement already satisfied: certifi>=2024.2.2 in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from curl_cffi>=0.7->yfinance) (2025.4.26)
Requirement already satisfied: pycparser in /home/danirm/.local/lib/python3.10/site-packages (from cffi>=1.12.0->curl_cffi>=0.7->yfinance) (2.21)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/danirm/.local/lib/python3.10/site-packages (from pandas>=1.3.0->yfinance) (2.8.2)
Requirement already satisfied: tzdata>=2022.7 in /home/danirm/.local/lib/python3.10/site-packages (from pandas>=1.3.0->yfinance) (2023.3)
Requirement already satisfied: six>=1.5 in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.17.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/danirm/.local/lib/python3.10/site-packages (from requests>=2.31->yfinance) (3.1.0)
Requirement already satisfied: idna<4,>=2.5 in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from requests>=2.31->yfinance) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/danirm/anaconda3/envs/proyecto_RL/lib/python3.10/site-packages (from requests>=2.31->yfinance) (1.26.20)

In [18]:
import pandas as pd
import numpy as np
import datetime
import yfinance as yf

from finrl.meta.preprocessor.yahoodownloader import YahooDownloader
from finrl.meta.preprocessor.preprocessors import FeatureEngineer, data_split
from finrl import config_tickers
from finrl.config import INDICATORS

import itertools

In [19]:
TRAIN_START_DATE = '2009-01-01'
TRAIN_END_DATE = '2020-07-01'
TRADE_START_DATE = '2020-07-01'
TRADE_END_DATE = '2023-05-01'

In [20]:
symbols = [
    'aapl',
    'msft',
    'meta',
    'ibm',
    'hd',
    'cat',
    'amzn',
    'intc',
    't',
    'v'
    'gs'
]

In [21]:
df_raw = YahooDownloader(start_date = TRAIN_START_DATE,
                                end_date = TRADE_END_DATE,
                                ticker_list = symbols).fetch_data()

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (32958, 8)

In [22]:
df_raw.head()

Price,date,close,high,low,open,volume,tic,day
0,2009-01-02,2.727417,2.736134,2.559415,2.581054,746015200,aapl,4
1,2009-01-02,2.718000,2.726500,2.553500,2.567500,145928000,amzn,4
2,2009-01-02,30.344679,30.389960,28.921564,29.050939,7117200,cat,4
3,2009-01-02,16.148619,16.188774,15.365615,15.439231,14902500,hd,4
4,2009-01-02,47.715294,47.835443,45.814766,45.814766,7905877,ibm,4

In [23]:
fe = FeatureEngineer(use_technical_indicator=True,
                     tech_indicator_list = INDICATORS,
                     use_vix=True,
                     use_turbulence=True,
                     user_defined_feature = False)

processed = fe.preprocess_data(df_raw)

[*********************100%***********************]  1 of 1 completed

Successfully added technical indicators
Shape of DataFrame:  (3604, 8)
Successfully added vix

Successfully added turbulence index

In [10]:
processed

,date,close,high,low,open,volume,tic,day,macd,boll_ub,boll_lb,rsi_30,cci_30,dx_30,close_30_sma,close_60_sma,vix,turbulence
0,2009-01-02,2.727417,2.736134,2.559415,2.581054,746015200,aapl,4,0.000000,2.947757,2.622185,100.000000,66.666667,100.000000,2.727417,2.727417,39.189999,0.000000
1,2009-01-02,2.718000,2.726500,2.553500,2.567500,145928000,amzn,4,0.000000,2.947757,2.622185,100.000000,66.666667,100.000000,2.718000,2.718000,39.189999,0.000000
2,2009-01-02,30.344679,30.389960,28.921564,29.050939,7117200,cat,4,0.000000,2.947757,2.622185,100.000000,66.666667,100.000000,30.344679,30.344679,39.189999,0.000000
3,2009-01-02,16.148619,16.188774,15.365615,15.439231,14902500,hd,4,0.000000,2.947757,2.622185,100.000000,66.666667,100.000000,16.148619,16.148619,39.189999,0.000000
4,2009-01-02,47.715294,47.835443,45.814766,45.814766,7905877,ibm,4,0.000000,2.947757,2.622185,100.000000,66.666667,100.000000,47.715294,47.715294,39.189999,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28827,2023-04-27,279.383636,280.125034,273.557001,273.747114,3133600,hd,3,0.841059,287.804455,271.096851,48.591925,15.605637,6.854106,276.560941,282.952745,17.030001,5.475535
28828,2023-04-27,116.618004,116.663923,115.231114,116.066924,3204900,ibm,3,-0.754802,122.295066,113.821231,44.911391,-38.238503,1.687847,117.341438,118.950495,17.030001,5.475535
28829,2023-04-27,29.144180,29.232023,27.826543,28.060789,60186200,intc,3,-0.018557,33.393174,28.197083,50.727398,-66.270249,13.386898,30.099059,28.330523,17.030001,5.475535
28830,2023-04-27,299.507843,299.871408,290.095117,290.802548,46462600,msft,3,5.050672,293.828175,271.060958,63.072929,228.848870,42.199524,278.830293,265.935451,17.030001,5.475535
28831,2023-04-27,15.620997,15.638737,15.399234,15.416974,36926900,t,3,-0.281713,18.553179,15.108712,42.445886,-113.201352,46.831442,16.631787,16.651582,17.030001,5.475535

In [24]:
list_ticker = processed["tic"].unique().tolist()
list_date = list(pd.date_range(processed['date'].min(),processed['date'].max()).astype(str))
combination = list(itertools.product(list_date,list_ticker))

processed_full = pd.DataFrame(combination,columns=["date","tic"]).merge(processed,on=["date","tic"],how="left")
processed_full = processed_full[processed_full['date'].isin(processed['date'])]
processed_full = processed_full.sort_values(['date','tic'])

processed_full = processed_full.fillna(0)

In [25]:
# Split the data
train = data_split(processed_full, TRAIN_START_DATE,TRAIN_END_DATE)
trade = data_split(processed_full, TRADE_START_DATE,TRADE_END_DATE)
print(len(train))
print(len(trade))

23144
5688

In [26]:
train

,date,tic,close,high,low,open,volume,day,macd,boll_ub,boll_lb,rsi_30,cci_30,dx_30,close_30_sma,close_60_sma,vix,turbulence
0,2009-01-02,aapl,2.727417,2.736134,2.559415,2.581054,746015200.0,4.0,0.000000,2.947757,2.622185,100.000000,66.666667,100.000000,2.727417,2.727417,39.189999,0.000000
0,2009-01-02,amzn,2.718000,2.726500,2.553500,2.567500,145928000.0,4.0,0.000000,2.947757,2.622185,100.000000,66.666667,100.000000,2.718000,2.718000,39.189999,0.000000
0,2009-01-02,cat,30.344679,30.389960,28.921564,29.050939,7117200.0,4.0,0.000000,2.947757,2.622185,100.000000,66.666667,100.000000,30.344679,30.344679,39.189999,0.000000
0,2009-01-02,hd,16.148619,16.188774,15.365615,15.439231,14902500.0,4.0,0.000000,2.947757,2.622185,100.000000,66.666667,100.000000,16.148619,16.148619,39.189999,0.000000
0,2009-01-02,ibm,47.715294,47.835443,45.814766,45.814766,7905877.0,4.0,0.000000,2.947757,2.622185,100.000000,66.666667,100.000000,47.715294,47.715294,39.189999,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2892,2020-06-30,hd,223.476715,224.493694,219.533692,220.345495,4524600.0,1.0,2.209611,230.758799,212.732471,56.635875,42.284210,8.960731,220.030361,205.619924,30.430000,4.528901
2892,2020-06-30,ibm,92.458649,92.787844,91.103578,91.249034,4099797.0,1.0,-0.894426,103.374418,86.383610,48.985987,-59.645526,2.646283,94.559642,93.104877,30.430000,4.528901
2892,2020-06-30,intc,53.335049,53.468763,52.185086,52.336630,31542100.0,1.0,-0.500384,57.582326,50.527436,50.231050,-73.270029,8.658016,54.523334,53.486025,30.430000,4.528901
2892,2020-06-30,msft,194.979996,195.832691,189.451852,189.585984,34310300.0,1.0,4.603375,197.144385,173.792845,60.679240,130.633141,29.206539,182.136554,175.005839,30.430000,4.528901
2892,2020-06-30,t,15.887904,15.945716,15.614609,15.772278,57979814.0,1.0,-0.120127,17.399340,14.957750,48.476211,-46.807096,1.084899,16.123886,15.889463,30.430000,4.528901

In [27]:
import pickle

with open("train.pkl", "wb") as f:
    pickle.dump(train, f)
    

with open("trade.pkl", "wb") as f:
    pickle.dump(trade, f)

In [13]:
processed_full

,date,tic,close,high,low,open,volume,day,macd,boll_ub,boll_lb,rsi_30,cci_30,dx_30,close_30_sma,close_60_sma,vix,turbulence
0,2009-01-02,aapl,2.727417,2.736134,2.559415,2.581054,746015200.0,4.0,0.000000,2.947757,2.622185,100.000000,66.666667,100.000000,2.727417,2.727417,39.189999,0.000000
1,2009-01-02,amzn,2.718000,2.726500,2.553500,2.567500,145928000.0,4.0,0.000000,2.947757,2.622185,100.000000,66.666667,100.000000,2.718000,2.718000,39.189999,0.000000
2,2009-01-02,cat,30.344679,30.389960,28.921564,29.050939,7117200.0,4.0,0.000000,2.947757,2.622185,100.000000,66.666667,100.000000,30.344679,30.344679,39.189999,0.000000
3,2009-01-02,hd,16.148619,16.188774,15.365615,15.439231,14902500.0,4.0,0.000000,2.947757,2.622185,100.000000,66.666667,100.000000,16.148619,16.148619,39.189999,0.000000
4,2009-01-02,ibm,47.715294,47.835443,45.814766,45.814766,7905877.0,4.0,0.000000,2.947757,2.622185,100.000000,66.666667,100.000000,47.715294,47.715294,39.189999,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41827,2023-04-27,hd,279.383636,280.125034,273.557001,273.747114,3133600.0,3.0,0.841059,287.804455,271.096851,48.591925,15.605637,6.854106,276.560941,282.952745,17.030001,5.475535
41828,2023-04-27,ibm,116.618004,116.663923,115.231114,116.066924,3204900.0,3.0,-0.754802,122.295066,113.821231,44.911391,-38.238503,1.687847,117.341438,118.950495,17.030001,5.475535
41829,2023-04-27,intc,29.144180,29.232023,27.826543,28.060789,60186200.0,3.0,-0.018557,33.393174,28.197083,50.727398,-66.270249,13.386898,30.099059,28.330523,17.030001,5.475535
41830,2023-04-27,msft,299.507843,299.871408,290.095117,290.802548,46462600.0,3.0,5.050672,293.828175,271.060958,63.072929,228.848870,42.199524,278.830293,265.935451,17.030001,5.475535
41831,2023-04-27,t,15.620997,15.638737,15.399234,15.416974,36926900.0,3.0,-0.281713,18.553179,15.108712,42.445886,-113.201352,46.831442,16.631787,16.651582,17.030001,5.475535